#include <iostream>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cassert>
#include "ais_bbox_mapper.hpp"
using namespace std;

AisBboxMapper::AisBboxMapper(AisUtil::GeoCoords currentLocation, AisUtil::GeoCoords lookAt)
    : currentLocation(currentLocation), lookAt(lookAt), cameraAngleInRadian(calculateAngleInRadian(currentLocation, lookAt)) {
}

AisBboxMapper::~AisBboxMapper() {
}

static const double DEG_TO_RAD = M_PI / 180.0;
AisUtil::GeoCoords AisBboxMapper::predictCurrentPosition(AisUtil::GeoCoords pos, double sog, double cog, double n) {
    // based on the artifact generated by ChatGPT (o1)

    double distance_nm = sog * (n / 3600.0);
    double cog_rad = cog * DEG_TO_RAD;
    double north_component = distance_nm * std::cos(cog_rad); 
    double east_component  = distance_nm * std::sin(cog_rad);

    double delta_lat_deg = north_component / 60.0;
    double lat_rad = pos.latitude * DEG_TO_RAD;
    double delta_lon_deg = east_component / (60.0 * std::cos(lat_rad));

    double new_lat = pos.latitude  + delta_lat_deg;
    double new_lon = pos.longitude + delta_lon_deg;

    return { new_lat, new_lon };
}

void AisBboxMapper::UpdateLocalShipInfo(time_t unixTime, const vector<AisUtil::ShipInfo>& shipInfoRef, uint32_t width, uint32_t height) {
    localShipInfo.clear();
    localShipScreenCoords.clear();
    const double angle = M_PI_2 - cameraAngleInRadian;
    for (auto it = shipInfoRef.begin(); it != shipInfoRef.end(); it++) {
        AisUtil::ShipInfo tmp = *it;

        // predict and adjust ship location based on COG and SOG
        auto elapsed = unixTime - tmp.unixTime ;
        assert(elapsed >= 0);
        if (tmp.sog != 0.0) {
            tmp.geoPos = predictCurrentPosition(tmp.geoPos, tmp.sog, tmp.cog, elapsed);
        }

        // rotate the point around currentLocation based on the camera's orientation
        tmp.geoPos = affineGeoCoords(tmp.geoPos, currentLocation, angle);
        tmp.cog += float(double(360) * angle / (double(2) * M_PI));
        AisUtil::NormalizeDegree(tmp.cog);

        localShipInfo.push_back(tmp);

        // calculate screen coords (TODO: this implementation is low precision. we will use perspective transform in the future)
        auto offsetX = 0;
        auto offsetY = height * 0.20f;
        auto scaleX = 25.0f;
        auto scaleY = 10.0f;
        auto newX = width / 2 + scaleX * float(tmp.geoPos.longitude * double(width)) + offsetX;
        auto newY = height - scaleY * float(tmp.geoPos.latitude  * double(height)) - offsetY;
        localShipScreenCoords.push_back({ newX, newY });
    }
}

vector<string> AisBboxMapper::SearchForShipName(detectNet::Detection* detections, int numDetections) {
    // convert bounding boxes to points
    detectedPoint.clear();
    for (int i = 0; i < numDetections; i++) {
        auto detection = detections[i];
        auto newX = detection.Left + (detection.Right  - detection.Left) / 2;
        auto newY = detection.Top  + (detection.Bottom - detection.Top)  / 2;
        detectedPoint.push_back({ newX, newY });
    }

    // calculate distance
    vector<tuple<double, int, int>> distance; // <distance, index of detections, index of localShipInfo>
    for (int i1 = 0; i1 < numDetections; i1++) {
        for (int i2 = 0; i2 < localShipScreenCoords.size(); i2++) {
            auto pos1 = detectedPoint[i1];
            auto pos2 = localShipScreenCoords[i2];
            auto d = pow(pos2.x - pos1.x, 2) + pow(pos2.y - pos1.y, 2);
            distance.push_back({ d, i1, i2 });
        }
    }
    sort(distance.begin(), distance.end());

#if 0
    int idx = 0;
    for (auto it = distance.begin(); it != distance.end(); it++) {
        cout << idx << ": " << get<0>(*it) << ", " << get<1>(*it) << ", " << get<2>(*it) << endl;
        idx++;
    }
#endif

    // select a candidate localShipInfo for each detection
    vector<string> shipNameList;
    for (int i = 0; i < numDetections; i++) {
        auto it = find_if(distance.begin(), distance.end(), [i](tuple<double, int, int> elm) {
            return get<1>(elm) == i;
        });
        if (it == distance.end()) {
            // no more candidates
            break;
        }

        // push shipName
        auto localShipId = get<2>(*it);
        shipNameList.push_back(localShipInfo[localShipId].shipName);

        // remove selected localShipInfo from distance
        auto it2 = remove_if(distance.begin(), distance.end(), [localShipId](tuple<double, int, int> elm) {
            return get<2>(elm) == localShipId;
        });
        if (it2 != distance.end()) {
            distance.erase(it2, distance.end());
        }
    }
    return shipNameList;
}

double AisBboxMapper::calculateAngleInRadian(AisUtil::GeoCoords p0, AisUtil::GeoCoords p) {
    double dx = p.longitude - p0.longitude;
    double dy = p.latitude  - p0.latitude;
    cout << "calculation of camera angle" << endl;
    cout << "dx = " << dx << ", dy = " << dy << endl;
    return atan2(dy, dx);
}

AisUtil::GeoCoords AisBboxMapper::affineGeoCoords(AisUtil::GeoCoords target, AisUtil::GeoCoords origin, double angle) {
    // rotate geoCoords around origin
    double cosVal = cos(angle);
    double sinVal = sin(angle);
    double dx = target.longitude - origin.longitude;
    double dy = target.latitude  - origin.latitude;
    double newX = dx * cosVal - dy * sinVal;
    double newY = dx * sinVal + dy * cosVal;
    return { newY, newX };
}

AisUtil::ScreenCoords AisBboxMapper::calculateScreenCoords(AisUtil::GeoCoords geoCoords) {
    auto offsetLatitude   = geoCoords.latitude  - currentLocation.latitude;
    auto offsetLongtitude = geoCoords.longitude - currentLocation.longitude;
}

void AisBboxMapper::PrintCurrentLocalShipInfo(stringstream* ss) {
    for (auto it = localShipInfo.begin(); it != localShipInfo.end(); it++) {
        AisUtil::PrintShipInfo(*it, ss);
    }
}

void AisBboxMapper::PrintCurrentLocalShipInfoSummary(stringstream* ss) {
    for (auto it = localShipInfo.begin(); it != localShipInfo.end(); it++) {
        AisUtil::PrintShipInfoSummary(*it, ss);
    }
}

const std::vector<AisUtil::ShipInfo>& AisBboxMapper::GetLocalShipInfo(void) {
    return localShipInfo;
}

const vector<AisUtil::ScreenCoords>& AisBboxMapper::GetDetectedPoint(void) {
    return detectedPoint;
}

const vector<AisUtil::ScreenCoords>& AisBboxMapper::GetLocalShipScreenCoords(void) {
    return localShipScreenCoords;
}