#include <iostream>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cassert>
#include "ais_bbox_mapper.hpp"
using namespace std;

AisBboxMapper::AisBboxMapper(const AisUtil::GeoCoords srcGeoPoints[], const cv::Point2f dstScreenPoints[]) {
    perspectiveMatrix = calculatePerspectiveMatrix(srcGeoPoints, dstScreenPoints);

#if 0
    cout << "Perspective Transformation Matrix:" << endl;
    for (int i = 0; i < perspectiveMatrix.rows; i++) {
        for (int j = 0; j < perspectiveMatrix.cols; j++) {
            cout << perspectiveMatrix.at<double>(i, j) << " ";
        }
        cout << endl;
    }
#endif
}

AisBboxMapper::~AisBboxMapper() {
}

static const double DEG_TO_RAD = M_PI / 180.0;
AisUtil::GeoCoords AisBboxMapper::predictCurrentPosition(AisUtil::GeoCoords pos, double sog, double cog, double n) {
    // based on the artifact generated by ChatGPT (o1)

    double distance_nm = sog * (n / 3600.0);
    double cog_rad = cog * DEG_TO_RAD;
    double north_component = distance_nm * std::cos(cog_rad); 
    double east_component  = distance_nm * std::sin(cog_rad);

    double delta_lat_deg = north_component / 60.0;
    double lat_rad = pos.latitude * DEG_TO_RAD;
    double delta_lon_deg = east_component / (60.0 * std::cos(lat_rad));

    double new_lat = pos.latitude  + delta_lat_deg;
    double new_lon = pos.longitude + delta_lon_deg;

    return { new_lat, new_lon };
}

void AisBboxMapper::UpdateLocalShipInfo(time_t unixTime, const vector<AisUtil::ShipInfo>& shipInfoRef) {
    localShipInfo.clear();
    localShipScreenCoords.clear();
    for (auto it = shipInfoRef.begin(); it != shipInfoRef.end(); it++) {
        AisUtil::ShipInfo tmp = *it;

        // predict and adjust ship location based on COG and SOG
        auto elapsed = unixTime - tmp.unixTime ;
        assert(elapsed >= 0);
        if (tmp.sog != 0.0) {
            tmp.geoPos = predictCurrentPosition(tmp.geoPos, tmp.sog, tmp.cog, elapsed);
        }

        localShipInfo.push_back(tmp);
        localShipScreenCoords.push_back(ConvertGeoCoordsToScreenCoords(tmp.geoPos));
    }
}

AisUtil::ScreenCoords AisBboxMapper::ConvertGeoCoordsToScreenCoords(const AisUtil::GeoCoords& geoPos) {
    // calculate screen coords using perspective matrix
    cv::Mat p0 = cv::Mat::zeros(3, 1, CV_64F);
    p0.at<double>(0, 0) = geoPos.longitude;
    p0.at<double>(1, 0) = geoPos.latitude;
    p0.at<double>(2, 0) = 1;
    cv::Mat p1 = perspectiveMatrix * p0;
    p1 /= p1.at<double>(2, 0);
    return { float(p1.at<double>(0, 0)), float(p1.at<double>(1, 0)) };
}

cv::Mat AisBboxMapper::calculatePerspectiveMatrix(const AisUtil::GeoCoords srcGeoPoints[], const cv::Point2f dstScreenPoints[]) {
    cv::Point2f srcScreenPoints[4];
    for (int i = 0; i < 4; i++) {
        auto tmp = srcGeoPoints[i];
        srcScreenPoints[i] = { tmp.longitude, tmp.latitude }; // AisUtil::GeoCoords -> cv::Point2f
    }
    return cv::getPerspectiveTransform(srcScreenPoints, dstScreenPoints);
}

vector<string> AisBboxMapper::SearchForShipName(detectNet::Detection* detections, int numDetections, float distanceThreshold) {
    // convert bounding boxes to points
    detectedPoint.clear();
    for (int i = 0; i < numDetections; i++) {
        auto detection = detections[i];
        auto newX = detection.Left + (detection.Right  - detection.Left) / 2;
        auto newY = detection.Top  + (detection.Bottom - detection.Top)  / 2;
        detectedPoint.push_back({ newX, newY });
    }

    // calculate distance
    vector<tuple<double, int, int>> distance; // <distance, index of detections, index of localShipInfo>
    for (int i1 = 0; i1 < numDetections; i1++) {
        for (int i2 = 0; i2 < localShipScreenCoords.size(); i2++) {
            auto pos1 = detectedPoint[i1];
            auto pos2 = localShipScreenCoords[i2];
            auto d = pow(pos2.x - pos1.x, 2) + pow(pos2.y - pos1.y, 2);
            distance.push_back({ d, i1, i2 });
        }
    }
    sort(distance.begin(), distance.end());

#if 0
    int idx = 0;
    for (auto it = distance.begin(); it != distance.end(); it++) {
        cout << idx << ": " << get<0>(*it) << ", " << get<1>(*it) << ", " << get<2>(*it) << endl;
        idx++;
    }
#endif

    // select a candidate localShipInfo for each detection
    vector<string> shipNameList;
    for (int i = 0; i < numDetections; i++) {
        string pushStr = "?";
        auto it = find_if(distance.begin(), distance.end(), [i](tuple<double, int, int> elm) {
            return get<1>(elm) == i;
        });
        if (it == distance.end()) {
            // no more candidates
            shipNameList.push_back(pushStr);
            continue; // push default string for remaining of numDetections
        }

        // push shipName
        auto localShipId = get<2>(*it);
        if (get<0>(*it) <= pow(distanceThreshold, 2)) {
            pushStr = localShipInfo[localShipId].shipName;
        }
        shipNameList.push_back(pushStr);

        // remove selected localShipInfo from distance
        auto it2 = remove_if(distance.begin(), distance.end(), [localShipId](tuple<double, int, int> elm) {
            return get<2>(elm) == localShipId;
        });
        if (it2 != distance.end()) {
            distance.erase(it2, distance.end());
        }
    }
    return shipNameList;
}

void AisBboxMapper::PrintCurrentLocalShipInfo(stringstream* ss) {
    for (int i = 0; i < localShipInfo.size(); i++) {
        AisUtil::PrintShipInfo(localShipInfo[i], ss);
        *ss << ", (" << localShipScreenCoords[i].x << "," << localShipScreenCoords[i].y << ")" << endl;
    }
}

void AisBboxMapper::PrintCurrentLocalShipInfoSummary(stringstream* ss) {
    for (int i = 0; i < localShipInfo.size(); i++) {
        AisUtil::PrintShipInfoSummary(localShipInfo[i], ss);
        *ss << ", (" << localShipScreenCoords[i].x << "," << localShipScreenCoords[i].y << ")" << endl;
    }
}

const std::vector<AisUtil::ShipInfo>& AisBboxMapper::GetLocalShipInfo(void) {
    return localShipInfo;
}

const vector<AisUtil::ScreenCoords>& AisBboxMapper::GetDetectedPoint(void) {
    return detectedPoint;
}

const vector<AisUtil::ScreenCoords>& AisBboxMapper::GetLocalShipScreenCoords(void) {
    return localShipScreenCoords;
}